spring:
  application:
    name: NOTIFICATION-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/app-changelog.xml
  cloud:
    zookeeper:
      config:
        enabled: false
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: gbhfns47@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: kNrIeJCEM6VWtpz35TAGhRsFQjyMnLf6
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Study-platform
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Study-platform
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8083