eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://95.163.230.65:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: 95.163.230.65
server:
  port: 8761
spring:
  application:
    name: service-registry
