spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://auth:8080/realms/Study-platform
        registration:
          gateway:
            provider: keycloak
            client-id: springsecurity
            client-secret: kNrIeJCEM6VWtpz35TAGhRsFQjyMnLf6
            authorization-grant-type: authorization_code
            scope:
              - openid
              - resource.read
  application:
    name: GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: notification-service
          uri: http://notifications-app:8083
          predicates:
            - Path=/api/notification/**
        - id: solution-service
          uri: http://solutions-app:8084
          predicates:
            - Path=/api/solution/**
        - id: user-service
          uri: http://user-app:8081
          predicates:
            - Path=/api/user/**
        - id: core-service
          uri: http://core-app:8082
          predicates:
            - Path=/api/learning/**
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Origin
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: service-registry
server:
  port: 9090