spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://postgres_user/javastudy_users_db
    username: postgres
    password: password123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/app-changelog.xml
  cloud:
    zookeeper:
      config:
        enabled: false
      enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: kNrIeJCEM6VWtpz35TAGhRsFQjyMnLf6
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://auth:8080/realms/Study-platform
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: http://auth:8080/realms/Study-platform
          jwk-set-uri: http://auth:8080/realms/Study-platform/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: http://broker:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

keycloak:
  server-url: http://auth:8080
  admin-client-id: admin-cli
  admin-client-secret: lpm8EeAJdDovYVtH34aUcluStO8CePYJ
  realm: Study-platform
  configuration: http://auth:8080/realms/Study-platform/.well-known/openid-configuration
