spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://95.163.230.65:5433/user
    username: postgres
    password: postgressergtosp
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/app-changelog.xml
  cloud:
    zookeeper:
      config:
        enabled: false
      enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: kNrIeJCEM6VWtpz35TAGhRsFQjyMnLf6
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Study-platform
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Study-platform
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

eureka:
  server:
    defaultZone: http://localhost:8761/eureka/
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

keycloak:
  server-url: http://localhost:8080
  admin-client-id: admin-cli
  admin-client-secret: lpm8EeAJdDovYVtH34aUcluStO8CePYJ
  realm: Study-platform
  configuration: http://localhost:8080/realms/Study-platform/.well-known/openid-configuration
