spring:
  application:
    name: SOLUTION-SERVICE
  datasource:
    url: jdbc:postgresql://postgres_solutions/solutions
    username: postgres
    password: postgressergtosp
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/app-changelog.xml
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: kNrIeJCEM6VWtpz35TAGhRsFQjyMnLf6
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://auth:8080/realms/Study-platform
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: http://auth:8080/realms/Study-platform
          jwk-set-uri: http://auth:8080/realms/Study-platform/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: broker:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

services:
  url: http://gateway:9090
  api-key: asfasgbasgqwfrqwgfvavashahnodqpwohqjm

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

docker:
  network: backend
  host: unix:///var/run/docker.sock