spring:
  application:
    name: CORE-SERVICE
  datasource:
    url: jdbc:postgresql://postgres_core/core
    username: postgres
    password: postgressergtosp
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/app-changelog.yaml
  cloud:
    zookeeper:
      config:
        enabled: false
      enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: 4aSFJvpqjsoc5oDkFSqivT1u6rImh2Yj
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://auth:8080/realms/Study-platform
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: http://auth:8080/realms/Study-platform
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8082

additional:
  api-key: asfasgbasgqwfrqwgfvavashahnodqpwohqjm

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true