spring:
  application:
    name: CORE-SERVICE
  datasource:
    url: jdbc:postgresql://95.163.230.65:5434/core
    username: postgres
    password: postgressergtosp
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/app-changelog.yaml
  cloud:
    zookeeper:
      config:
        enabled: false
      enabled: false
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: springsecurity
#            client-secret: 4aSFJvpqjsoc5oDkFSqivT1u6rImh2Yj
#            authorization-grant-type: authorization_code
#            scope:
#              - openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/Study-platform
#            user-name-attribute: preferred_username
#
#
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/Study-platform
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://95.163.230.65:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8082